export const COUNTRIES_REQUEST_BEGIN = 'COUNTRIES_REQUEST_BEGIN';
export const COUNTRIES_REQUEST_SUCCESS = 'COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILURE = 'COUNTRIES_REQUEST_FAILURE';
export const FILTER_CHANGE = 'FILTER_CHANGE';